### ISSUE TITLE
Resource file search error

### ISSUE THREAD

**Issue by Janyau** [dictlab/mdict-cpp#37]
First of all, I would like to express my sincere gratitude to the author for his hard work!!!

### System environment
macOS  15.0.1

### Operation steps
- Query worded__gb_1.mp3
```shell
./mydict /Users/**/Library/Containers/com.test.**/Data/Library/Application\ Support/Dictionaries/oaldpe/oaldpe.1.mdd \\worded__gb_1.mp3
```

- Return result
After converting the returned base64, it turns out to be: "word_perfect_1_gb_1.mp3"

- How to verify
Write the base64 string to the hard disk using Python

```python
import base64

data = "..."
mp3_bytes = base64.b64decode(data)
with open("output.mp3", "wb") as f:
    f.write(mp3_bytes)
```

mdd file link: https://pan.baidu.com/s/17h8m3JbC0JHac-2zBDDC5Q?pwd=6ccg 提取码: 6ccg

**Comment by Janyau** [comment]
@terasum Many thanks. This mdx dictionary file is a bit large.(1.5GB). 

mdx: https://pan.baidu.com/share/link?shareid=434963&uk=2902556240

**Comment by KonstantinDjairo** [comment]
hello @Janyau , you shouldn't save directly to your disk when doing lookups.
the purpose of having base64 output in this library is that you can render the media without needing to save it as a file.

when the html is gathered from a lookup, you can recursively lookup each media, and the result (which is a proper base64 html string) can be directly replaced into the original html, thus generating a completely standalone html that doesn't load anything from disk.

I've already implemented it in my haskell project, which uses mdict-cpp
https://git.ajattix.org/hashirama/mdict-hs/src/branch/main/MDict.hs
(see the media related functions)

**Comment by KonstantinDjairo** [comment]
as for "getting incorrect files"
i should mention that under unix environments (such as mac/bsd/linux" all the queries must be inside of quotes , like this:
```shell
$ ./test dict.mdx "\graphics\kanji.png"
```

otherwise lookup can fail , because the slashes are getting treated badly

**Comment by Janyau** [comment]
@KonstantinDjairo , Thanks for getting back to me! 
In my project(macOS App), I imported the static library (.a) into the project. When I queried the resource file, I just returned the data to the webview!

Now, I have tried the way you mentioned below:
```
./mydict /Users/*/Documents/GitSpot/WordCatcher\ Prototype/Dic/Oxford/OALD\ 2024.09/oaldpe.1.mdd "\worded__gb_1.mp3"
```
but I still get the wrong file.

**Comment by KonstantinDjairo** [comment]
> [@KonstantinDjairo](https://github.com/KonstantinDjairo) , Thanks for getting back to me! In my project(macOS App), I imported the static library (.a) into the project. When I queried the resource file, I just returned the data to the webview!
> 
> Now, I have tried the way you mentioned below:
> 
> ```
> ./mydict /Users/*/Documents/GitSpot/WordCatcher\ Prototype/Dic/Oxford/OALD\ 2024.09/oaldpe.1.mdd "\worded__gb_1.mp3"
> ```
> 
> but I still get the wrong file.

rendering directly in a webView was a smart approach !
I'll download your Oxford dictionary later and debug it, can be an error related to the dictionary file itself.

since i have experience with [dictionary production](dictionaries.ajattix.org), i can check the health of the file

**Comment by KonstantinDjairo** [comment]
> [@Janyau](https://github.com/Janyau) [@KonstantinDjairo](https://github.com/KonstantinDjairo) there is a quick way to verify the dictionary is broken or not. Just use nodejs version js-mdict command:
> 
> js-mdict yourmddfile.mdd \\assets\\your_resource_key.mp3

yes, indeed.
but mdict-cpp is stable as by now, and I've tested it in dozens of dictionaries, so i bet there's some kind of problem in his mdd file, should be also worth mentioning that we have unit tests for each major feature (as by now powered by googletests, but I'll change to acutest in the future)

**Comment by KonstantinDjairo** [comment]
> [@KonstantinDjairo](https://github.com/KonstantinDjairo) Thank you very much for your hint! I use the Node.js version of the 'js-mdict' command to verify whether the dictionary is damaged. Finally, the 'js-mdict' give me the right source.
> 
> ```
>  js-mdict  /Users/*/Library/Containers/com/Data/Library/Application\ Support/Dictionaries/oaldpe/oaldpe.1.mdd  \\worded__gb_1.mp3  -f
> ```
> 
> [js-mdict](https://github.com/terasum/js-mdict)

interesting, but i think there's still a need to confirm whether mdict-cpp really has a bug or not.
it's worth noting that every mdict that I've test was made with: https://github.com/liuyug/mdict-utils

so they aren't malformed
